modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Fire%20Spread%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="firespreadtweaks"
version="2.7"
displayName="Fire Spread Tweaks"
displayURL="https://serilum.com/mod/fire-spread-tweaks"
authors="Rick South"
description='''Disables the default firespread, but does make fire go out on its own after a configurable delay.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.firespreadtweaks]]
    modId="collective"
    type="required"
    versionRange="[7.86,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firespreadtweaks]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "firespreadtweaks.mixins.json"